default_platform(:android)

platform :android do
  fastfileLocation = File.expand_path(File.dirname(__FILE__))
  
  lane :increment_version_code do |options|
    build_number = Integer(options[:build_number])
    puts(build_number: build_number)

    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    s[re, 1] = String(build_number)

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
  
  desc 'Clean project'
  lane :clean do
    gradle(
      task: 'clean',
    )
  end

  desc 'Build the Android application'
  lane :build do
    keystore_path = "#{fastfileLocation}/../keystore/keystore/application.keystore"
    clean
    gradle(
      task: 'bundle',
      flavor: ENV['FLAVOR'],
      build_type: 'release',
      properties: {
        'android.injected.signing.store.file' => keystore_path,
        'android.injected.signing.store.password' => ENV['KEYSTORE_PASSWORD'],
        'android.injected.signing.key.alias' => ENV['KEYSTORE_ALIAS'],
        'android.injected.signing.key.password' => ENV['KEYSTORE_ALIAS_PASSWORD']
      }
    )
  end

end
