default_platform(:android)

def set_version_code(version_code)
  path = '../app/build.gradle'
  re = /versionCode\s+(\d+)/

  s = File.read(path)
  s[re, 1] = String(version_code)

  f = File.new(path, 'w')
  f.write(s)
  f.close
end

platform :android do
  fastfileLocation = File.expand_path(File.dirname(__FILE__))

  desc 'Increment build number'
  lane :increment_build do
    previous_build_number = google_play_track_version_codes(
      track: "internal",
    )[0]

    current_build_number = previous_build_number + 1

    set_version_code(current_build_number);

    git_commit(path: "./app/build.gradle", message: "Set new version code to #{current_build_number}")

    push_to_git_remote(
      remote: "origin"
    )
  end
  
  desc 'Clean project'
  lane :clean do
    gradle(
      task: 'clean',
    )
  end

  desc 'Build the Android application'
  lane :build do
    keystore_path = "#{fastfileLocation}/../application.keystore"
    clean
    gradle(
      task: 'bundle',
      flavor: ENV['FLAVOR'],
      build_type: 'release',
      properties: {
        'android.injected.signing.store.file' => keystore_path,
        'android.injected.signing.store.password' => ENV['KEYSTORE_PASSWORD'],
        'android.injected.signing.key.alias' => ENV['KEYSTORE_ALIAS'],
        'android.injected.signing.key.password' => ENV['KEYSTORE_ALIAS_PASSWORD']
      }
    )
  end

  desc 'Deploy the application'
  lane :beta do
    build
    upload_to_play_store(track: 'internal')
  end

end
